### ISSUE TITLE
TinyMCE HTML Is Sometimes Stripped

### ISSUE THREAD

**Issue by maxdumas** [TechAtNYU/intranet#111]
Just tried to submit a details field on an event with `<ul>` and `<li>` tags and they were stripped from the submitted HTML, even though they were supported by the editor. (The button was available in the toolbar and the WYSIWYG worked.) @ethanresnick any ideas why this might happen? Could it be an issue on the API's side?

It's worth noting that wrapping `<p>` tags in the submitted HTML weren't stripped.

**Comment by ethanresnick** [comment]
@maxdumas Can you try POSTing/PATCHing to the api directly, without going through the intranet ui, in order to isolate the culprit? I don't think it's the api, but I'm not sure.

**Comment by maxdumas** [comment]
As an update: It looks like TinyMCE on the front end is actually never generating the correct HTML/binding it to the model in the first place. Looking at the source window in the actual editor shows that no real HTML is generated. So this is definitely a front-end issue. Whether or not it's an issue with *our* code or angular-tinymce I'm going to look into now.

**Comment by maxdumas** [comment]
Ethan made a typo. :)

**Comment by ethanresnick** [comment]
#ethanfail

**Comment by ethanresnick** [comment]
P.S. Attributes are still getting stripped

**Comment by ethanresnick** [comment]
@maxdumas Any idea why this is still happening?

**Comment by ethanresnick** [comment]
This bug may be caused by/related to the TinyMCE textarea showing up even on some fields that don't take HTML. For example, I just loaded the related clubs add form, and the "Name" field was a tinymce input, even though the API docs return `allowedHtml: null` for that field, which should make this test fail.

Note: the API docs are not consistent. Sometimes, plain-text-only fields have `allowedHtml: null` and other times their description simply doesn't have an `allowedHtml` key at all. (The difference comes from whether the field's been explicitly marked on the backend as not allowing HTML.) But, in either case, the intranet should not use a Tinymce field.

**Comment by maxdumas** [comment]
[The check against `allowedHtml` is for a truthy value](https://github.com/TechAtNYU/intranet/blob/master/app/js/services/form-element-provider.js#L16), so it shouldn't give a false-positive if it is `undefined`. That said, check out [edit](http://intranet.sexy/#/r/related-clubs/edit/548112cac0e3d27ee9073d26) for related versus [add](http://intranet.sexy/#/r/related-clubs/add). Now *that* is weird. I'm going to make a separate issue for that.

**Comment by maxdumas** [comment]
Closing this as the issue it identifies has been resolved. See #118 and #119 for follow-up issues.
