### ISSUE TITLE
Readonly fields shouldn't be patched

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#74]
Right now does the `facebookId` get PATCHED back when a user has been edited? We don't necessarily want it to get PATCHED back. I think it is right now!

Just check if the field is read-only across all resources, and not PATCH those.

**Comment by maxdumas** [comment]
@ethanresnick Is this really an issue? Would the API allow this change on its end? I'm prioritizing right now and I'll fix this if it's a potential vulnerability but the API should block this anyway.

**Comment by ethanresnick** [comment]
So, here's the thing: before the api was accepting POSTs/PATCHes that contained read only fields, but it was just silently ignoring the provided values. Now, as soon as https://github.com/TechAtNYU/api/commit/84b797d5cbfb8cad843db37c88a79d4cd78c80c0 is deployed, it'll dos the correct thing and return a `403 Forbidden`. But, from the intranet's point of view, this actually makes the problem much worse, because now **any attempt to create or update a resource that has a read-only field will fail,** because the intranet provides some value for those fields in its request and that results in an error.

To make this concrete: the POST to create a person that the intranet makes will now 403 because that POST contains `facebookId` and `roles` keys, even though it leaves their values empty. And requests to update a person will fail because the request contains `facebookId` and `roles` values—irrespective of the fact that those values happen to be the same as they were when the intranet did a GET for the resource.

Now, there are a few ways to handle this:

1. The API could go back to silently ignoring the provided value. This is pretty ugly theoretically, but it also causes a practical problem, namely: soon there will be fields that aren't readonly (in the sense of _always_ being unmodifiable and documented as such) but are still not modifiable *by the current user*. For example, it may be that any board member can edit the `attendees` of an external event, but that, for internal events, only members of the teams hosting the event can edit the attendees (so that, for example, only the President could mark someone as present at an eboard meeting). In these cases, the intranet will need to know whether the update was actually accepted or not, and it will want to be able to do this based on the status code rather than having to actually inspect the response payload. So returning 403, rather than 200 and silent ignore, matters in this case.

2. So, we could have the API accept PATCHes that contain readonly fields, as long as the values for those fields in the PATCH are the same as the old values the resource had. But this would still be theoretically yucky for some cases. The best example is modified date (which will soon be marked as readonly): the value of PATCH might match the old modified date, but the PATCHed resource will have a new modified date after the PATCH succeeds. So, if the API accepts the PATCH with the old modified date and gives a 200 OK, it would be signaling to the client that the resource's modified date matches the value in the PATCH, when, in fact, it doesn't. This theoretical mistake wouldn't have any negative practical consequences yet, but its still ugly. There's also a practical problem, though, namely: that to check if the incoming values match the old values, the API would have to query the database to get the existing state of the resource, which would (dramatically) slow down every PATCH. So this option's no good either.

3. Therefore, I think that leaves the intranet simply not including readonly fields (in both PATCH and POST) as the only option. But, because, as I explained above, some fields might be unmodifiable by the current user without being documented as readonly, the intranet will have to go farther to make sure its updates actually succeed. Namely, it will have to only include in the PATCH fields that the user *actually changed*, which means it'll need some dirty checking logic. This has been theoretically necessary from the start—a PATCH really shouldn't send be sending back values the user didn't touch, as that just opens the door for two people editing a resource simultaneously to inadvertently overwrite each other. But now that we're running into practical use cases for it, this dirty checking logic needs to be higher priority.

The simplest version of dirty checking that we can get away with for now is what @abhiagarwal said when opening this issue: namely, just assume that readonly values are never dirty and all others are. But we'll have to get more sophisticated soon.

**Comment by maxdumas** [comment]
I'll look into this, but the good news is that Angular is really great
about keeping track dirty/pristine fields (It does it automatically.)and
gives some good tools to work with them. It will definitely take a bit of
doing but this shouldn't be a major roadblock.

**Comment by ethanresnick** [comment]
@maxdumas Yay!
