### ISSUE TITLE
Dates in List View should be in EST

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#99]
(Or, for a more generic solution, in the user's computer's local time.)

Right now, they're in UTC

**Comment by maxdumas** [comment]
This again ties into #71, though it does bring up an interesting point, in that the solution to #71 will need to be able to handle custom formatting at multiple levels. I'm going to bring this up inside that issue. I want to hear your thoughts on this as I think I am going to try to implement that next because this seems like it is causing most of our usability issues right now.

**Comment by ethanresnick** [comment]
I'm happy to work through with you what kinds of flexibility we're likely to need over time--though I feel like I'm pretty underqualified to suggest _how_ to structure the angular app to support that flexibility. 

I tried to capture my preliminary thinking on what we'll in the wizard system issue, but some of that may be revisited. And the general amount of customization needed is probably going to skyrocket the more we think about real ux design, which will offer more nuanced solutions than the auto generation.

**Comment by ashleytqy** [comment]
fixed by https://github.com/TechAtNYU/intranet/pull/200
